# Generated by Django 2.1.7 on 2019-03-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190304_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airports',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
