# Generated by Django 2.1.7 on 2019-03-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190304_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcompany',
            name='iata',
            field=models.CharField(default='', max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
