# Generated by Django 2.1.7 on 2019-03-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_flightcompany_iata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightcompany',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
