# Generated by Django 2.1.7 on 2019-03-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190304_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcompany',
            name='icao',
            field=models.CharField(default='', max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flightcompany',
            name='iata',
            field=models.CharField(max_length=2),
        ),
    ]
