# Generated by Django 2.1.7 on 2019-03-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190304_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightcompany',
            name='id',
        ),
        migrations.AlterField(
            model_name='flightcompany',
            name='icao',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
