# Generated by Django 2.1.7 on 2019-03-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190304_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='company',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='route',
        ),
        migrations.RemoveField(
            model_name='route',
            name='dst',
        ),
        migrations.RemoveField(
            model_name='route',
            name='src',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
