# Generated by Django 2.1.7 on 2019-03-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_flightcompany_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightcompany',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='airlines'),
        ),
    ]
