# Generated by Django 2.1.7 on 2019-03-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='prod_images'),
            preserve_default=False,
        ),
    ]
