# Generated by Django 2.1.7 on 2019-03-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='country',
        ),
        migrations.AddField(
            model_name='recommend',
            name='country',
            field=models.ManyToManyField(to='core.Countries'),
        ),
    ]
