# Generated by Django 2.1.7 on 2019-03-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190305_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Countries')),
            ],
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='country',
        ),
        migrations.AddField(
            model_name='recommendcountry',
            name='recommend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Recommend'),
        ),
    ]
