# Generated by Django 2.1.7 on 2019-03-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='store',
            new_name='store_old',
        ),
    ]
