# Generated by Django 2.1.7 on 2019-03-05 14:22

from django.db import migrations


def fill_stores(apps, schema_editor):
    Product = apps.get_model('core', 'Product')
    Store = apps.get_model('core', 'Store')
    products = Product.objects.all()
    for product in products:
        store, created = Store.objects.get_or_create(name=product.store_old)
        if created:
            store.cashback = product.cashback
        store.save()


def unfill_stores(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0017_auto_20190305_1421'),
    ]

    operations = [
        migrations.RunPython(fill_stores, unfill_stores),
    ]
