# Generated by Django 2.1.7 on 2019-03-05 14:54

from django.db import migrations


def fill_stores(apps, schema_editor):
    Product = apps.get_model('core', 'Product')
    Store = apps.get_model('core', 'Store')
    products = Product.objects.all()
    for product in products:
        product.store = Store.objects.get(name=product.store_old)
        product.save()


def unfill_stores(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0020_remove_product_cashback'),
    ]

    operations = [
        migrations.RunPython(fill_stores, unfill_stores),
    ]
