# Generated by Django 2.1.7 on 2019-03-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190305_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store_old',
        ),
    ]
