# Generated by Django 2.1.7 on 2019-03-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190305_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='alpha2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
