# Generated by Django 2.1.7 on 2019-03-05 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_countries_alpha2'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Countries'),
        ),
    ]
