# Generated by Django 2.1.7 on 2019-03-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_store_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='country',
        ),
    ]
