# Generated by Django 2.1.7 on 2019-03-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_store_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storedelivery_dst', to='core.Countries')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storedelivery_src', to='core.Countries')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Store')),
            ],
        ),
    ]
