# Generated by Django 2.1.7 on 2019-03-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_storedelivery'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storedelivery',
            unique_together={('store', 'src', 'dst')},
        ),
    ]
