# Generated by Django 2.1.7 on 2019-03-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190305_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedelivery',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
