# Generated by Django 2.1.7 on 2019-03-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_storedelivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedelivery',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
