# Generated by Django 2.1.7 on 2019-03-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190305_2025'),
        ('core', '0030_auto_20190305_2040'),
    ]

    operations = [
    ]
