apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hackaton
  namespace: edc-catalog
  labels:
    app: hackaton
spec:
  selector:
    matchLabels:
      app: hackaton
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hackaton
    spec:
      containers:
        - name: hackaton
          image: gcr.io/qa-edc-ew/hackaton:latest
          imagePullPolicy: Always
          env:
            - name: DATABASE_HOST
              value: edc-catalog-db
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: edc-catalog-db-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: edc-catalog-db-secret
                  key: password
          ports:
            - containerPort: 8000
