apiVersion: v1
kind: Service
metadata:
  name: hackaton
  namespace: edc-catalog
  labels:
    app: hackaton
spec:
  type: LoadBalancer
  loadBalancerIP: "35.225.11.75"
  ports:
    - port: 8000
  selector:
    app: hackaton
